### ISSUE TITLE
Problems plotting FOE

### ISSUE THREAD

**Issue by joakim-hove** [Ensembles/ert#1032]
[ This is copied from: https://github.com/OPM/opm-core/issues/981 ]

I run some simulations on OPM, I wanted to plot the Field Oil Recovery. In order to do that I created a file that I called foe.py (see below) and I placed it in the folder ert/devel/python/python/ert/ecl. The name of the file was added to the CMakeLists.txt present in the same folder as foe.py. The ert program was then compiled using cmake and make.

After that procedure I was not able to see the "foip vs date" appear on the Terminal (I'm using Ubuntu).
foe.py file:

```python
#!/usr/bin/env python
import sys
from ert.ecl import EclGrid, EclFile

base_name = sys.argv[1]
grid = EclGrid("%s.EGRID")
rst_file = EclFile("%s.UNRST")

for date in rst_file.dates:
   rst_file.select_restart_section( sim_time = date )
   swat = rst_file["SWAT"][0]
   sgas = rst_file["SGAS"][0]
   rst_file.select_global()

   soil = 1 - swat - sgas

   foip = 0
   for index in range(len(soil)):
      cell_volume = grid.cell_volume( active_index = index )
      foip += cell_volume * soil[index]

   print "Date:%s  FOIP:%g" % (date , foip)    
```

**Comment by joakim-hove** [comment]
OK;

Before you do *anything else* - make sure you *have installed* the `ert.ecl` Python package correctly. To check that just type:
```txt
bash% python -m ert
```
in your terminal. That should give you the output:
```txt
`/usr/bin/python: No module named ert.__main__; 'ert' is a package and cannot be directly executed
```
If you instead get: 
```
/usr/bin/python: No module named ert
```
you have not installed the `ert.ecl` Python package correctly. That must be fixed first.

**Comment by joakim-hove** [comment]
*When* you have verified that the `ert.ecl` package is indeed correctly installed, you are ready to run your script. The `foe.py` script *uses* the `ert.ecl` package, but it should *not* be compiled/bundled with the rest of the `ert.ecl` distribution - just put it *anywhere*[1] in the filesystem - and execute it from there. *If* the `ert.ecl` package has been correctly installed the script will find the package; otherwise you will get an `ImportError` from the Python interpreter.

[1]: For convenience you could put it in a personal `bin/` folder - if you have on. Where to put the script is really about Linux `PATH` behavior, and nothing else.

**Comment by imperial-1** [comment]
Thank very much for your contribution.  ert.ecl is intalled. Th script  seems not working. I have got the following  error:
/tmp
Traceback (most recent call last):
  File "foe.py", line 13, in <module>
    grid = EclGrid("%s.EGRID")
  File "/usr/local/lib/python2.7/dist-packages/ert/ecl/ecl_grid.py", line 176, in __new__
    raise IOError("Loading grid from:%s failed" % filename)
IOError: Loading grid from:%s.EGRID failed
root@ese-mk218:/home/mk812# python foe.py /tmp
  File "foe.py", line 6
SyntaxError: Non-ASCII character '\xe2' in file foe.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by imperial-1** [comment]
I run the script using the shell command: python foe.py /tmp

**Comment by joakim-hove** [comment]
> ert.ecl is installed

Good

> Th script seems not working.

Well - this script was something I wrote directly into the Github comment window in three minutes - of course it has bugs. I think learning a script language like Python will serve you well in your PhD - but then you should be able to debug this script:

Hint1:
```python
...
raise IOError("Loading grid from:%s failed" % filename)
IOError: Loading grid from:%s.EGRID failed
```

Hint2: https://docs.python.org/2/library/stdtypes.html#string-formatting

**Comment by joakim-hove** [comment]
> I run the script using the shell command: `python foe.py /tmp`

Well - that is wrong in 1.5 ways:

1. When the script starts with `#!/usr/bin/env python` you can just make it executable with `chmod u+x foe.py` - and then run it with the shell command `foe.py BASE` - i.e. without the leading `python` - although I do not think the leading Python hurts.

2. The commandline argument to the script should be the basename of the output files, i.e. if you after the simulation have files `MY_CASE.EGRID, MY_CASE.UNRST, MY_CASE.UNSMRY`and so on you should invoke the script as `foe.py MY_CASE` - alternatively you can supply a leading path component first - as in `foe.py /path/to/simulations/MY_CASE`.

**Comment by imperial-1** [comment]
Dear Joakim: I modified the script and it is running now:

**Comment by imperial-1** [comment]
To calculate the recovery factor: 
1. put the following file in the folder where you simulation files are (DATA file, EGRID file, UNRST file....)

# -*coding:Utf -8 -*
#!/usr/bin/env python

import sys
from ert.ecl import EclGrid, EclFile
 
base_name = sys.argv[1]
grid = EclGrid( "2D_THREEPHASE_POLY_HETER.EGRID")
rst_file = EclFile( "2D_THREEPHASE_POLY_HETER.UNRST")  # Assuming the restart file is unified.


i=0
 
for date in rst_file.dates:

     i+=1
     rst_file.select_restart_section( sim_time = date )
     swat = rst_file["SWAT"][0]
     sgas = rst_file["SGAS"][0]
     rst_file.select_global()
 
     soil = 1 - swat - sgas
 
     foip = 0
     for index in range(len(soil)):
          cell_volume = grid.cell_volume( active_index = index )
          foip += cell_volume * soil[index]
     if i==1:
	foipi=foip
    
     print "Date:%s  FOIP:%g" % (date , foip)    


RF=foip/foipi

print ("Final Recovery Factor=", RF)

**Comment by imperial-1** [comment]
2. you need to specify the name of your DATA file in the script, i.e. replace in the script above 2D_THREEPHASE_POLY_HETER by the name of your DATA file

3. you need to run the script contained in the file (name foe.py for instance). To do that you need the use the following commands in your Terminal (in the case of linux):

chmod +x foe.py

then: 

python foe.py NAME_OF_YOUR_DATA_FILE 
( For  exemple: python foe.py 2D_THREEPHASE_POLY_HETER)

**Comment by pgdr** [comment]
It seems that the issue has been solved, and I am therefore closing this.  Please reopen if necessary.

**Comment by pgdr** [comment]
Thanks for the feedback, @imperial-1 !
