### ISSUE TITLE
Plugin MDA crashes when runpath folder is empty

### ISSUE THREAD

**Issue by pgdr** [Ensembles/ert#1086]
To reproduce, clear runpath folder (make sure there are no realisation-X/iter-Y folders) and run MDA smoother plugin.

Error message: job_queue_add_job: failed to create job SNAKE_OIL_0 in path: /private/pgdr/ert/snake_oil/storage/snake_oil/runpath/realisation-0/iter-0 cwd:/private/pgdr/ert/snake_oil

After going to runpath, one can see that folder remains empty.

Full error log:

    Abort called from: job_queue_add_job (/private/pgdr/ert/ert/devel/libjob_queue/src/job_queue.c:1140) 
    
    Error message: job_queue_add_job: failed to create job SNAKE_OIL_0 in path: /private/pgdr/ert/snake_oil/storage/snake_oil/runpath/realisation-0/iter-0 cwd:/private/pgdr/ert/snake_oil 
    
    
    
    --------------------------------------------------------------------------------
     #00 ???? 
     #01 util_abort__(..)                                                              in ???
     #02 job_queue_add_job(..)                                                         in ???
     #03 enkf_main_isubmit_job(..)                                                     in ???
     #04 enkf_main_isubmit_job__(..)                                                   in ???
     #05 ???? 
     #06 ???? 
     #07 clone(..)                                                                     in ???
    --------------------------------------------------------------------------------

Possibly related to 2951e31

**Comment by arielalmendral** [comment]
Yes, related. I fix.

**Comment by pgdr** [comment]
Fixed in #1087.
