### ISSUE TITLE
Improve error message when UTIL_FREAD_SCALAR crashes on end-of-stream

### ISSUE THREAD

**Issue by pgdr** [Ensembles/ert#1149]
In `util.c` and `util.h`.  If the following function is called with `stream` at end, the error message will be "SUCCESS".
```c
int util_fread_int(FILE * stream) {
  int file_value;
  UTIL_FREAD_SCALAR(file_value , stream);
  return file_value;
}
```
This is caused by the fact that

1.  `fread` returns 0 because it cannot read anything (we are at the end of the stream)
2.  We verify that indeed 1 byte has been read (it hasn't)
3.  We print `errno` set by `fread`.  However, `fread` doesn't consider reaching end-of-stream an error and sets `errno=0` indicating no error

Solution:  If returned value and `errno` both are 0, the error message should indicate that we (prematurely) reached end-of-stream.

**Comment by joakim-hove** [comment]
Fixed: https://github.com/Ensembles/ert/pull/1161/commits/be9acebc9f8127f9d87c28505f587c4a71268774
