### ISSUE TITLE
create3D problem

### ISSUE THREAD

**Issue by cfbe** [Ensembles/ert#1197]
The create3D function has stopped working. This was working some weeks ago.

tr-linrgsn016:~/cc/opm/opm-data/spe1:$ ll
total 493
drwxrwx--- 2 cfbe cfbe  1288 May 26 08:43 eclipse-simulation
drwxrwx--- 2 cfbe cfbe   332 May 26 08:43 opm-simulation-reference
-rw-rw---- 1 cfbe cfbe 11602 May 26 08:43 SPE1CASE1.DATA
-rw-rw---- 1 cfbe cfbe 11583 May 26 08:43 SPE1CASE2.DATA
-rw-rw---- 1 cfbe cfbe 11958 May 26 08:43 SPE1CASE2_FAMII.DATA
-rw-rw---- 1 cfbe cfbe 11623 May 26 08:43 SPE1CASE2_RESTART.DATA
-rw-rw---- 1 cfbe cfbe 11568 May 26 08:43 SPE1CASE2_SLGOF.DATA
tr-linrgsn016:~/cc/opm/opm-data/spe1:$ python
Python 2.7.11 (default, Jan  7 2016, 10:13:26) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import ert.ecl as ecl
>>> gridfile='eclipse-simulation/SPE1CASE1'
>>> grid=ecl.EclGrid(gridfile+".EGRID")
>>> rst_file = ecl.EclFile(gridfile+'.UNRST')
>>> swat_kw = rst_file.iget_named_kw( "SWAT" , 0 )
>>> swat3D = grid.create3D(swat_kw)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/res/x86_64_RH_6/share/ert/release/stable/python/ert/ecl/ecl_grid.py", line 1097, in create3D
    array = array.reshape( [self.ngetNX() , self.getNY() , self.getNZ()] , order = 'F')
AttributeError: 'EclGrid' object has no attribute 'ngetNX'

**Comment by joakim-hove** [comment]
Thank you - we will fix this quite fast.

**Comment by pgdr** [comment]
Fixed in _Numpy 3d fixup_ #1198.

**Comment by cfbe** [comment]
It works now, thanks.
