### ISSUE TITLE
Test failures in FortIO / EclFile

### ISSUE THREAD

**Issue by pgdr** [Ensembles/ert#1201]
Two tests fail consequently in my Ubuntu install of Ert, and they fail at least 50% of the time in my Redhat 7 install of Ert:

```
Test #209: python.tests.ecl.ecl_deprecation2.0 ...***Failed
Test #211: python.tests.ecl.fortio ..........***Failed
```

Both tests fail in `EclFile` while trying to open a FortIO file,

```
209: Traceback (most recent call last):
209:   File "/home/pgd/ert/ert/build/lib/python2.7/dist-packages/tests/ecl/test_deprecation.py", line 57, in test_EclFile_name_property
209:     f = EclFile( "TEST" )
209:   File "/home/pgd/ert/ert/build/lib/python2.7/dist-packages/ert/ecl/ecl_file.py", line 247, in __init__
209:     raise IOError("Failed to open file file:%s" % filename)
209: IOError: Failed to open file file:TEST
```

The failures might be related to flush/sync issues internally in the python/c-interface.

**Comment by pgdr** [comment]
Ps., My Ubuntu is 16.04.1 (Linux 4.4) with Python 2.7.12.

**Comment by joakim-hove** [comment]
Try this: https://github.com/Ensembles/ert/pull/1223?

**Comment by pgdr** [comment]
This will be dealt with when we successfully make ert Python 3 compatible.  In the mean time, if no users experience issues with this, we will leave this dormant.
