### ISSUE TITLE
Missing return statement in ecl_nnc_equal

### ISSUE THREAD

**Issue by blattms** [Ensembles/ert#1244]
I know this is not C++ (undefined behaviour) and I am not sure how C treats missing return statements. But this warning bothers me a bit:
```
/home/mblatt/DUNE/ert/libecl/src/ecl_nnc_export.c: In function ‘ecl_nnc_equal’:
/home/mblatt/DUNE/ert/libecl/src/ecl_nnc_export.c:144:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```
Wouldn't rewriting [ecl_nnc_equal](/Ensembles/ert/blob/030f7a5dd5c725a6a52fed1e56b231765501a8c1/libecl/src/ecl_nnc_export.c#L141-L142) as
```c++
return (ecl_nnc_sort_cmp( nnc1 , nnc2) == 0) &&
    ((nnc1->trans == nnc2->trans) && (nnc1->input_index == nnc2->input_index));
```
do the right thing without any warning (and possible bug)?

**Comment by joakim-hove** [comment]
It should be fixed - is already fixed in a feature branch.

**Comment by blattms** [comment]
Great!
