### ISSUE TITLE
Simulation run path creation

### ISSUE THREAD

**Issue by agchitu** [Ensembles/ert#1261]
The ertshell seems not to allow for the creation of the simulation path. A new menu entry has been introduced in the ert-tui ("cC") but that does not yet have a correspondent in the ertshell.

**Comment by joakim-hove** [comment]
> The ertshell seems not to allow for the creation of the simulation path. A new menu entry has been introduced in the ert-tui ("cC") but that does not yet have a correspondent in the ertshell.

The ert-tui is in deep deep maintenance mode, and no new menu entries have been introduced there for several years. But - adding an option to create runpath directories from the ertshell sounds like a good idea. Feel very free to add PR starting from here: https://github.com/Ensembles/ert/blob/master/python/python/ert_gui/shell/simulations.py

**Comment by pgdr** [comment]
Please reopen at [Statoil/libres](https://github.com/Statoil/libres) if this is still an issue.
