### ISSUE TITLE
Launching LSF server on RHEL6

### ISSUE THREAD

**Issue by chewson** [Ensembles/ert#1339]
I have some issues running an ERT case on RHEL6 using the LSF server (v8.3). It is a local LSF queue on the machine and the config file runs when launched locally, but trying to use the LSF queue system within ert (tui, shell and gui) causes a signal 11. Message received is as follows:

```
Abort called from: util_abort_signal (/uhome/hewsoncw/ert/libert_util/src/util.c:4942)

Error message: Program received signal:11

--------------------------------------------------------------------------------
 #00 ????
 #01 util_abort__(..)                                                              in ???
 #02 ????
 #03 ????
 #04 lsf_driver_alloc_cmd(..)                                                      in ???
 #05 lsf_driver_submit_job(..)                                                     in ???
 #06 job_queue_node_submit(..)                                                     in ???
 #07 job_queue_run_jobs(..)                                                        in ???
 #08 job_queue_run_jobs__(..)                                                      in ???
 #09 ????
 #10 clone(..)                                                                     in ???
--------------------------------------------------------------------------------
Aborted (core dumped)
```

with no further information in the log file:

01/12 - 14:35:00  All jobs submitted to internal queue - waiting for completion
01/12 - 14:35:13  ert configuration loaded
01/12 - 14:35:47  ===================================================================

The configuration options used in the ERT config were:

```
QUEUE_SYSTEM         LSF
LSF_SERVER           <redacted - but full server name and tried local>
QUEUE_OPTION LSF MAX_RUNNING   20
QUEUE_OPTION LSF  BJOBS_CMD  /opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bjobs
QUEUE_OPTION LSF  BSUB_CMD   /opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bsub
QUEUE_OPTION LSF  BKILL_CMD /opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bkill
```

also tried without the B.... options. Considering just modifying the jobs to submit to the queue system themselves, but any help or explanation for this for future use would be excellent.

Chris@TNO

**Comment by pgdr** [comment]
Please reopen at [Statoil/libres](https://github.com/Statoil/libres) if this is still an issue.
