### ISSUE TITLE
Generated python scripts broken for python 3.4

### ISSUE THREAD

**Issue by blattms** [Ensembles/ert#1346]
```
[ 56%] Generating ../../../lib/python3.4/dist-packages/cwrap/clib.py
py_compile(/home/mblatt/src/dune/opm/ert-build/lib/python3.4/dist-packages/cwrap/clib.py) failed:  File "/home/mblatt/src/dune/opm/ert-build/lib/python3.4/dist-packages/cwrap/clib.py", line 86
    except Exception, exc:
                    ^
SyntaxError: invalid syntax

python/python/cwrap/CMakeFiles/cwrap.dir/build.make:85: recipe for target 'lib/python3.4/dist-packages/cwrap/clib.py' failed
make[2]: *** [lib/python3.4/dist-packages/cwrap/clib.py] Error 1
CMakeFiles/Makefile2:1425: recipe for target 'python/python/cwrap/CMakeFiles/cwrap.dir/all' failed
make[1]: *** [python/python/cwrap/CMakeFiles/cwrap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Compilation exited abnormally with code 2 at Mon Dec  5 20:52:00
```

I assume that the correct syntax would be
```python
except Exception as exc:
```

**Comment by blattms** [comment]
Seems like ert is using python3 on my system now. (I might have installed it recently).

**Comment by blattms** [comment]
Deleting CMakeCache.txt and rerunning cmake it used version 2.7. There is a warning, though
```
-- Could NOT find PythonInterp: Found unsuitable version "2.7.9", but required is exact version "2.7" (found /usr/bin/python)
```
Closing as invalid. Sorry for the noise.

**Comment by pgdr** [comment]
> Closing as invalid. Sorry for the noise.

No noise, on the contrary, thank you for sharing your experiences.  We are aware of the shortcomings when it comes to python 3, and this reminds us that obvious fixes like `Exception, exc` should be fixed when encountered.

I will fix this one, but there are (much) bigger problems to deal with before we can try to begin testing with Python 3.

Thanks again for the report!
