### ISSUE TITLE
Small issue with python 3.4

### ISSUE THREAD

**Issue by dr-robertk** [Ensembles/ert#1431]
The file python/python/ert/ecl/ecl_rft.py contains a tab in line 91 which prevents from the package from building with python 3.4. Replacing the tab with white spaces fixes the issue.

**Comment by joakim-hove** [comment]
OK - cool; we will fix that. Be aware that there are more fundamental issues than space/tabs which prevents fully functional Python3 support - but we are on it.

**Comment by pgdr** [comment]
That's freakin' embarrassing!

#1432 fixes this.
