### ISSUE TITLE
DeprecationWarnings weren't issued

### ISSUE THREAD

**Issue by pgdr** [Ensembles/ert#1437]
`DeprecationWarning`s are silenced by default in python 2.7 and later.  If we want users to see the deprecation warning, we need to explicitly turn it off in our modules.

```python
In [1]: import warnings
In [2]: warnings.simplefilter('always', DeprecationWarning)
In [3]: warnings.warn('test', DeprecationWarning)
/usr/bin/ipython:1: DeprecationWarning: test
  #!/usr/bin/python2
```

versus

```
In [1]: import warnings
In [2]: warnings.warn('test', DeprecationWarning)
```

See also #1358.

**Comment by joakim-hove** [comment]
>  If we want users to see the deprecation warning, we need to explicitly turn it off in our modules.

Just to get this 100% clear: "If we want the users to see the deprecation warnings we need to explicitly turn *off the silencing* - i.e. 
```python
import warnings
warnings.simplefilter('always', DeprecationWarning)
```
in the `ert/__init__.py` file will ensure that all deprecation warnings are shown to the user. If I have understood the situation correctly I would like this as a PR.

**Comment by pgdr** [comment]
>> If we want users to see the deprecation warning, we need to explicitly turn it off in our modules.

> Just to get this 100% clear: "If we want the users to see the deprecation warnings we need to explicitly turn _off the silencing_

Yes.

> in the `ert/__init__.py` file will ensure that all deprecation warnings are shown to the user

I believe so, yes.

I will make a PR.
