### ISSUE TITLE
Initialization hangs when out of bounds realization number is asked for

### ISSUE THREAD

**Issue by berland** [Ensembles/ert#489]
If we have set
NUM_REALIZATIONS 50

and then ask to run realization number 443 for example:
==> x
Which realizations to simulate (Ex: 1,3-5) [M to return to menu] : => 443

Then ERT is "initializing" for ever instead of giving an error message.

**Comment by pgdr** [comment]
This is tracked internally.

_Internal: ERT-1120_

**Comment by pgdr** [comment]
Hangs at `enkf_main.c->enkf_main_run_step->job_queue_manager_wait( queue_manager );`

Fix suggested #1394.
