### ISSUE TITLE
enkf_types undefined or invalid?

### ISSUE THREAD

**Issue by rolk** [Ensembles/ert#680]
In file `devel/libenkf/src/enkf_types.c`, function `enkf_types_get_state_enum__`, there is first a test for UNDEFINED (on line 85) and then if there is no match, there is a catch-all which returns INVALID (on line 89).

However, there is no member INVALID in `state_enum` (defined in  `devel/libenkf/include/ert/enkf/enkf_types.h`, line 114).  There is one in ert_impl_type right above, but it is defined to the same value as UNDEFINED (=0). So, what should be the semantics of this routine. Why not return UNDEFINED in all cases where it is not {FORECAST, ANALYZED, BOTH}?

(And, there is a test in devel/libenkf/src/enkf_types.c:125 which tests for this value, which generate a warning that can be fixed, based on that answer :-))

**Comment by pgdr** [comment]
This is outdated.  If this is still an issue, please reopen.
