### ISSUE TITLE
abs instead fabs

### ISSUE THREAD

**Issue by rafuck** [Ensembles/ert#761]
There are too many warnings
1) of such kind 
./ert-master/devel/libecl/src/ecl_kw.c:419:1: note: use function 'fabsf' instead
./ert-master/devel/libecl/src/ecl_kw.c:409:8: note: expanded from macro 'CMP'
  if ((abs(v1) + abs(v2)) == 0)                                  \
       ^
./ert/ert-master/devel/libecl/src/ecl_kw.c:419:1: warning: using integer absolute value function 'abs' when argument is of floating point type
      [-Wabsolute-value]
CMP(float)

2) or such:
./ert/ert-master/devel/libecl/src/point.c:57:41: warning: using integer absolute value function 'abs' when argument is of floating point type
      [-Wabsolute-value]
  double diff_y = (abs(p1->y - p2->y) / abs(p1->y + p2->y + 1));
                                        ^
./ert/ert-master/devel/libecl/src/point.c:57:41: note: use function 'fabs' instead
  double diff_y = (abs(p1->y - p2->y) / abs(p1->y + p2->y + 1));

**Comment by joakim-hove** [comment]
> There are too many warnings

Yes you are right - but thanks for pointing out, it gives further impetus to improve the situation. The abs / fabs issue you point to was quite bad. Will fix.

**Comment by joakim-hove** [comment]
Fixed in this commit:https://github.com/joakim-hove/ert/commit/d6b2807ea1cc5d83f7e73c84a767498c5adaafa5
